---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - networking.sealos.io
  resources:
  - portfeedrequests
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networking.sealos.io
  resources:
  - portfeedrequests/finalizers
  verbs:
  - update
- apiGroups:
  - networking.sealos.io
  resources:
  - portfeedrequests/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - networking.sealos.io
  resources:
  - trafficsyncrequests
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networking.sealos.io
  resources:
  - trafficsyncrequests/finalizers
  verbs:
  - update
- apiGroups:
  - networking.sealos.io
  resources:
  - trafficsyncrequests/status
  verbs:
  - get
  - patch
  - update
