# permissions for end users to edit trafficsyncrequests.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: trafficsyncrequest-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: sealos-nm-synchronizer
    app.kubernetes.io/part-of: sealos-nm-synchronizer
    app.kubernetes.io/managed-by: kustomize
  name: trafficsyncrequest-editor-role
rules:
- apiGroups:
  - networking.sealos.io
  resources:
  - trafficsyncrequests
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networking.sealos.io
  resources:
  - trafficsyncrequests/status
  verbs:
  - get
