apiVersion: networking.sealos.io/v1alpha1
kind: TrafficSyncRequest
metadata:
  labels:
    app.kubernetes.io/name: trafficsyncrequest
    app.kubernetes.io/instance: trafficsyncrequest-sample
    app.kubernetes.io/part-of: sealos-nm-synchronizer
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: sealos-nm-synchronizer
  name: trafficsyncrequest-sample
spec:
  associatedNamespace: "my-ns"
  associatedPod: "my-pod"
  ciliumEndpointID: 1872
  nodeIP: "192.168.0.104"
  address: "10.0.0.279"
  tags:
    - "world"
    - "80"
  syncPeriod: "1m"
  
